import { describe, it, expect } from 'vitest'
import {
  createSpoolGeometry,
  torqueFromForce,
  correctedTorqueNm,
  rawTorqueNmForCorrected,
  forceNFromMassKg,
  massKgFromForceN,
} from '../cableGeometry'

// Cross-checks createSpoolGeometry()'s piecewise growth-calibration mirror
// (train_tab_build_spec.md "calibration overhaul" item 3b) against
// core/cable/geometry.py's SpoolGeometry -- the reference values below were
// generated by running the exact same (r0, points) through the Python
// class directly, not hand-derived, so this pins the JS mirror to the real
// implementation rather than to another guess at the same formula.
describe('createSpoolGeometry (piecewise growth model)', () => {
  const r0 = 0.06
  const points = [
    [2.0, 0.7],
    [5.0, 1.55],
    [10.0, 2.7],
  ]
  const geometry = createSpoolGeometry(r0, 0.0, points)

  it.each([
    [0.0, 0.0, 0.06],
    [1.0, 0.36349555921538756, 0.05570423008216337],
    [2.0, 0.7, 0.051408460164326736],
    [3.5, 1.1547566611769184, 0.04509390054270369],
    [5.0, 1.5500000000000003, 0.03877934092108064],
    [7.0, 2.0263893421169303, 0.03704037771312487],
    [10.0, 2.7, 0.034431932901191224],
    [15.0, 3.7134221490255808, 0.03008452488130181],
  ])('turnsDelta=%f matches geometry.py length and r_eff', (turnsDelta, expectedLengthM, expectedREffM) => {
    expect(geometry.lengthFromTurnsDelta(turnsDelta)).toBeCloseTo(expectedLengthM, 9)
    expect(geometry.rEffAtTurnsDelta(turnsDelta)).toBeCloseTo(expectedREffM, 9)
  })

  it('reduces to the flat r0/k model when growthPoints is empty', () => {
    const flat = createSpoolGeometry(0.05, 0.001, [])
    // r_eff(theta) = r0 + k*theta, theta = turnsDelta * 2*pi
    const turnsDelta = 3.0
    const theta = turnsDelta * 2 * Math.PI
    expect(flat.rEffAtTurnsDelta(turnsDelta)).toBeCloseTo(0.05 + 0.001 * theta, 9)
    expect(flat.lengthFromTurnsDelta(turnsDelta)).toBeCloseTo(0.05 * theta + (0.001 / 2) * theta * theta, 9)
  })

  it('reduces to plain r0 when both k=0 and growthPoints is empty', () => {
    const bare = createSpoolGeometry(0.035, 0.0, [])
    expect(bare.rEffAtTurnsDelta(4.0)).toBeCloseTo(0.035, 9)
  })

  it('clamps r_eff to minREffM past the calibrated envelope', () => {
    // Same shrinking-radius scenario as
    // core/tests/test_train_mode.py::test_tick_clamps_effective_radius_to_min_floor_beyond_calibrated_envelope
    // -- the model's raw extrapolation goes negative far past the one
    // calibration point; the floor must still hold client-side.
    const shrinking = createSpoolGeometry(0.06, 0.0, [[2.0, 0.363]], 0.005)
    expect(shrinking.rEffAtTurnsDelta(50.0)).toBe(0.005)
  })
})

describe('torqueFromForce (items 2/6 -- Testing tab torque-limit unit conversion)', () => {
  it('is the inverse of forceFromTorque', () => {
    expect(torqueFromForce(40, 0.04)).toBeCloseTo(1.6, 9)
  })
})

describe('correctedTorqueNm / rawTorqueNmForCorrected (items 6/7)', () => {
  it('is identity at the default (uncalibrated) scale/offset', () => {
    expect(correctedTorqueNm(0.35)).toBeCloseTo(0.35, 9)
    expect(rawTorqueNmForCorrected(0.35)).toBeCloseTo(0.35, 9)
  })

  it('are inverses of each other under a real calibration', () => {
    const scale = 1.1
    const offset = 0.05
    const raw = 0.4
    const corrected = correctedTorqueNm(raw, scale, offset)
    expect(rawTorqueNmForCorrected(corrected, scale, offset)).toBeCloseTo(raw, 9)
  })

  it('rawTorqueNmForCorrected does not divide by zero at scale=0', () => {
    expect(rawTorqueNmForCorrected(5.0, 0, 1.0)).toBe(0)
  })

  // Sign-preserving, magnitude-only correction (5 Aug 2026 fix -- mirrors
  // core/cable/torque_calibration.py's same fix): scale/offset correct the
  // MAGNITUDE of the reading, direction passes through untouched. Confirms
  // the JS mirror matches the Python original's corrected behavior.
  it('correctedTorqueNm preserves the sign of raw and corrects only the magnitude', () => {
    const scale = 0.5
    const offset = 1.2
    const positive = correctedTorqueNm(0.9, scale, offset)
    const negative = correctedTorqueNm(-0.9, scale, offset)
    expect(positive).toBeGreaterThan(0)
    expect(negative).toBeCloseTo(-positive, 9)
  })

  it('correctedTorqueNm of exactly zero is zero even with a nonzero offset', () => {
    expect(correctedTorqueNm(0, 0.5, 1.2)).toBe(0)
  })

  it('rawTorqueNmForCorrected preserves sign and floors magnitude at zero below offset', () => {
    const scale = 0.5
    const offset = 1.2
    expect(rawTorqueNmForCorrected(-2.0, scale, offset)).toBeCloseTo(-rawTorqueNmForCorrected(2.0, scale, offset), 9)
    // corrected magnitude smaller than offset -> no valid raw magnitude,
    // floors at 0 (toBeCloseTo, not toBe -- the negative branch legitimately
    // produces -0, which is numerically 0 but fails Object.is-based toBe)
    expect(rawTorqueNmForCorrected(0.5, scale, offset)).toBeCloseTo(0, 9)
    expect(rawTorqueNmForCorrected(-0.5, scale, offset)).toBeCloseTo(0, 9)
  })
})

describe('forceNFromMassKg / massKgFromForceN (item 2 -- resistance display unit preference)', () => {
  it('are inverses of each other', () => {
    expect(massKgFromForceN(forceNFromMassKg(5.0))).toBeCloseTo(5.0, 9)
  })

  it('matches the known g=9.81 conversion', () => {
    expect(forceNFromMassKg(10.0)).toBeCloseTo(98.1, 9)
  })
})
