import { describe, it, expect } from 'vitest'
import { createSpoolGeometry } from '../cableGeometry'

// Cross-checks createSpoolGeometry()'s piecewise growth-calibration mirror
// (train_tab_build_spec.md "calibration overhaul" item 3b) against
// core/cable/geometry.py's SpoolGeometry -- the reference values below were
// generated by running the exact same (r0, points) through the Python
// class directly, not hand-derived, so this pins the JS mirror to the real
// implementation rather than to another guess at the same formula.
describe('createSpoolGeometry (piecewise growth model)', () => {
  const r0 = 0.06
  const points = [
    [2.0, 0.7],
    [5.0, 1.55],
    [10.0, 2.7],
  ]
  const geometry = createSpoolGeometry(r0, 0.0, points)

  it.each([
    [0.0, 0.0, 0.06],
    [1.0, 0.36349555921538756, 0.05570423008216337],
    [2.0, 0.7, 0.051408460164326736],
    [3.5, 1.1547566611769184, 0.04509390054270369],
    [5.0, 1.5500000000000003, 0.03877934092108064],
    [7.0, 2.0263893421169303, 0.03704037771312487],
    [10.0, 2.7, 0.034431932901191224],
    [15.0, 3.7134221490255808, 0.03008452488130181],
  ])('turnsDelta=%f matches geometry.py length and r_eff', (turnsDelta, expectedLengthM, expectedREffM) => {
    expect(geometry.lengthFromTurnsDelta(turnsDelta)).toBeCloseTo(expectedLengthM, 9)
    expect(geometry.rEffAtTurnsDelta(turnsDelta)).toBeCloseTo(expectedREffM, 9)
  })

  it('reduces to the flat r0/k model when growthPoints is empty', () => {
    const flat = createSpoolGeometry(0.05, 0.001, [])
    // r_eff(theta) = r0 + k*theta, theta = turnsDelta * 2*pi
    const turnsDelta = 3.0
    const theta = turnsDelta * 2 * Math.PI
    expect(flat.rEffAtTurnsDelta(turnsDelta)).toBeCloseTo(0.05 + 0.001 * theta, 9)
    expect(flat.lengthFromTurnsDelta(turnsDelta)).toBeCloseTo(0.05 * theta + (0.001 / 2) * theta * theta, 9)
  })

  it('reduces to plain r0 when both k=0 and growthPoints is empty', () => {
    const bare = createSpoolGeometry(0.035, 0.0, [])
    expect(bare.rEffAtTurnsDelta(4.0)).toBeCloseTo(0.035, 9)
  })

  it('clamps r_eff to minREffM past the calibrated envelope', () => {
    // Same shrinking-radius scenario as
    // core/tests/test_train_mode.py::test_tick_clamps_effective_radius_to_min_floor_beyond_calibrated_envelope
    // -- the model's raw extrapolation goes negative far past the one
    // calibration point; the floor must still hold client-side.
    const shrinking = createSpoolGeometry(0.06, 0.0, [[2.0, 0.363]], 0.005)
    expect(shrinking.rEffAtTurnsDelta(50.0)).toBe(0.005)
  })
})
